const cervezas=  [
    {
      "id": 1,
      "nombre": "Cerveza Artesanal Sierra Andina Pachacutec Botella",
      "descripcion": "Una cerveza artesanal de sabor suave y refrescante, con notas de cítricos y un ligero toque de caramelo. Perfecta para los amantes de la cerveza.",
      "categoria": "Ale",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695688934/HopPassion/1.png",
      "precio_dolares": 3.99,
      "pais_origen": "Argentina",
      "grados_alcohol": 10.5,
      "cantidad": 330
    },
    {
      "id": 2,
      "nombre": "Cerveza Artesanal Sierra Andina Shaman Botella",
      "descripcion": "Una cerveza exótica con un aroma único a frutas tropicales y especias. Su sabor intenso y afrutado la hace ideal para ocasiones especiales.",
      "categoria": "Fruit Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695688983/HopPassion/2.png",
      "precio_dolares": 4.49,
      "pais_origen": "Perú",
      "grados_alcohol": 8,
      "cantidad": 330
    },
    {
      "id": 3,
      "nombre": "REVELATION V.S.O.B.",
      "descripcion": "Una cerveza robusta y llena de carácter, con notas de café y chocolate negro. Perfecta para los amantes de las cervezas oscuras.",
      "categoria": "Stout",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689024/HopPassion/3.png",
      "precio_dolares": 5.99,
      "pais_origen": "México",
      "grados_alcohol": 10.3,
      "cantidad": 330
    },
    {
      "id": 4,
      "nombre": "CERVEZA AGUILA",
      "descripcion": "Una cerveza refrescante con un toque de limón y hierbas frescas. Ideal para disfrutar en días calurosos.",
      "categoria": "Wheat Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689036/HopPassion/4.png",
      "precio_dolares": 6.29,
      "pais_origen": "Colombia",
      "grados_alcohol": 4.8,
      "cantidad": 355
    },
    {
      "id": 5,
      "nombre": "CERVEZA CORONA",
      "descripcion": "Una cerveza clara y ligera con un sabor suave y equilibrado. Perfecta para acompañar cualquier comida.",
      "categoria": "Lager",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689059/HopPassion/5.png",
      "precio_dolares": 4.99,
      "pais_origen": "Mexico",
      "grados_alcohol": 4.0,
      "cantidad": 355
    },
    {
      "id": 6,
      "nombre": "Cerveza Tropical Limón",
      "descripcion": "Una cerveza tropical con un aroma a piña y limon. Su sabor fresco y afrutado te transportará a una playa paradisíaca.",
      "categoria": "Fruit Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689071/HopPassion/6.png",
      "precio_dolares": 3.79,
      "pais_origen": "Perú",
      "grados_alcohol": 5.5,
      "cantidad": 355
    },
    {
      "id": 7,
      "nombre": "Cerveza Desperados Original",
      "descripcion": "Una cerveza picante con un toque de chiles ahumados y especias. Para los amantes de las emociones fuertes.",
      "categoria": "Spicy Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689078/HopPassion/7.png",
      "precio_dolares": 4.99,
      "pais_origen": "México",
      "grados_alcohol": 5.9,
      "cantidad": 330
    },
    {
      "id": 8,
      "nombre": "CERVEZA ARTESANAL ECOMIKHUNA PALE ALE",
      "descripcion": "Una cerveza tradicional con raíces históricas y un sabor auténtico. Ideal para quienes aprecian la herencia cervecera.",
      "categoria": "Traditional Ale",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689092/HopPassion/8.png",
      "precio_dolares": 5.49,
      "pais_origen": "Colombia",
      "grados_alcohol": 4.2,
      "cantidad": 330
    },
    {
      "id": 9,
      "nombre": "Citrus Imperial",
      "descripcion": "Una cerveza de invierno con notas de canela y nuez moscada. Perfecta para calentarse en las noches frías.",
      "categoria": "Winter Warmer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689101/HopPassion/9.png",
      "precio_dolares": 4.29,
      "pais_origen": "Argentina",
      "grados_alcohol": 6.0,
      "cantidad": 330
    },
    {
      "id": 10,
      "nombre": "CERVEZA HOLLANDIA PREMIUM",
      "descripcion": "Una cerveza ligera y baja en calorías, ideal para mantenerse en forma sin renunciar al sabor.",
      "categoria": "Light Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689111/HopPassion/10.png",
      "precio_dolares": 3.49,
      "pais_origen": "Perú",
      "grados_alcohol": 4.7,
      "cantidad": 330
    },
    {
      "id": 11,
      "nombre": "Cerveza artesanal magic quinua",
      "descripcion": "Una cerveza mágica que cambia de color con la temperatura. Descubre un arco iris de sabores a medida que se calienta.",
      "categoria": "Mystical Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689127/HopPassion/11.png",
      "precio_dolares": 6.99,
      "pais_origen": "México",
      "grados_alcohol": 5.0,
      "cantidad": 269
    },
    {
      "id": 12,
      "nombre": "Cerveza Dorada Pilsen",
      "descripcion": "Una cerveza dorada con un toque de miel y vainilla. Su sabor dulce y suave la hace perfecta para los paladares más exigentes.",
      "categoria": "Golden Ale",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689138/HopPassion/12.png",
      "precio_dolares": 5.79,
      "pais_origen": "Peru",
      "grados_alcohol": 6.2,
      "cantidad": 269
    },
    {
      "id": 13,
      "nombre": "Cerveza Duvel",
      "descripcion": "Una cerveza refinada con un toque de madera y vainilla. Envejecida en barricas de roble para un sabor excepcional.",
      "categoria": "Barrel-Aged Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689148/HopPassion/13.png",
      "precio_dolares": 7.99,
      "pais_origen": "Argentina",
      "grados_alcohol": 8.5,
      "cantidad": 269
    },
    {
      "id": 14,
      "nombre": "Cerveza Artesanal La Ñusta",
      "descripcion": "Una cerveza frutal con un aroma a frutas del bosque y un sabor refrescante. Ideal para los amantes de los sabores naturales.",
      "categoria": "Fruit Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689167/HopPassion/14.png",
      "precio_dolares": 4.49,
      "pais_origen": "Perú",
      "grados_alcohol": 5.5,
      "cantidad": 355
    },
    {
      "id": 15,
      "nombre": "Cerveza ahumada RAUCHBOCK",
      "descripcion": "Una cerveza ahumada con un toque de malta tostada y humo. Perfecta para acompañar carnes a la parrilla.",
      "categoria": "Smoked Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689191/HopPassion/15.png",
      "precio_dolares": 6.79,
      "pais_origen": "México",
      "grados_alcohol": 7.8,
      "cantidad": 355
    },
    {
      "id": 16,
      "nombre": "Cerveza Bitburger Premium",
      "descripcion": "Una cerveza premium con un sabor suave y refinado, enriquecido con lúpulos aromáticos. Para ocasiones especiales.",
      "categoria": "Premium Lager",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689200/HopPassion/16.png",
      "precio_dolares": 7.49,
      "pais_origen": "Colombia",
      "grados_alcohol": 5.9,
      "cantidad": 500
    },
    {
      "id": 17,
      "nombre": "RTD Corona Tropical Frutos Rojos",
      "descripcion": "Una cerveza tropical con un aroma a Frutos Rojos. Su sabor fresco y afrutado te transportará a una playa paradisíaca.",
      "categoria": "Fruit Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689208/HopPassion/17.png",
      "precio_dolares": 4.99,
      "pais_origen": "Argentina",
      "grados_alcohol": 4.2,
      "cantidad": 355
    },
    {
      "id": 18,
      "nombre": "Cerveza Mahou Negra",
      "descripcion": "Una cerveza con un fuerte sabor a café recién tostado y un toque de chocolate negro. Ideal para los amantes del café.",
      "categoria": "Coffee Stout",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689214/HopPassion/18.png",
      "precio_dolares": 6.99,
      "pais_origen": "Perú",
      "grados_alcohol": 7.5,
      "cantidad": 330
    },
    {
      "id": 19,
      "nombre": "Cerveza artesanal Beer Stache",
      "descripcion": "Una cerveza refrescante con un toque de limón y hierbas frescas. Ideal para disfrutar en días calurosos.",
      "categoria": "Wheat Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689220/HopPassion/19.png",
      "precio_dolares": 5.29,
      "pais_origen": "México",
      "grados_alcohol": 4.5,
      "cantidad": 330
    },
    {
      "id": 20,
      "nombre": "CERVEZA LA TRAPPE TRIPEL",
      "descripcion": "Una cerveza ligera y baja en calorías, ideal para mantenerse en forma sin renunciar al sabor.",
      "categoria": "Light Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689225/HopPassion/20.png",
      "precio_dolares": 3.79,
      "pais_origen": "Colombia",
      "grados_alcohol": 3.8,
      "cantidad": 330
    },
    {
      "id": 21,
      "nombre": "Cerveza artesanal rompeolas",
      "descripcion": "Una cerveza exótica con un aroma único a frutas tropicales y especias. Su sabor intenso y afrutado la hace ideal para ocasiones especiales.",
      "categoria": "Fruit Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689234/HopPassion/21.png",
      "precio_dolares": 4.99,
      "pais_origen": "Argentina",
      "grados_alcohol": 6.5,
      "cantidad": 330
    },
    {
      "id": 22,
      "nombre": "Cerveza Sapporo",
      "descripcion": "Una cerveza premium con un sabor suave y refinado, enriquecido con lúpulos aromáticos. Para ocasiones especiales.",
      "categoria": "Premium Lager",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689250/HopPassion/22.png",
      "precio_dolares": 6.79,
      "pais_origen": "Perú",
      "grados_alcohol": 5.9,
      "cantidad": 355
    },
    {
      "id": 23,
      "nombre": "CERVEZA PAULANER WEISSBIER",
      "descripcion": "Una cerveza robusta y llena de carácter, con notas de café y chocolate negro. Perfecta para los amantes de las cervezas oscuras.",
      "categoria": "Stout",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689257/HopPassion/23.png",
      "precio_dolares": 5.79,
      "pais_origen": "México",
      "grados_alcohol": 7.2,
      "cantidad": 500
    },
    {
      "id": 24,
      "nombre": "Cerveza 7 Vidas American Red",
      "descripcion": "Una cerveza tradicional con raíces históricas y un sabor auténtico. Ideal para quienes aprecian la herencia cervecera.",
      "categoria": "Traditional Ale",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689262/HopPassion/24.png",
      "precio_dolares": 4.29,
      "pais_origen": "Colombia",
      "grados_alcohol": 5.2,
      "cantidad": 340
    },
    {
      "id": 25,
      "nombre": "Cerveza Negra Modelo",
      "descripcion": "Una cerveza de invierno con notas de canela y nuez moscada. Perfecta para calentarse en las noches frías.",
      "categoria": "Winter Warmer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689268/HopPassion/25.png",
      "precio_dolares": 7.49,
      "pais_origen": "Argentina",
      "grados_alcohol": 6.0,
      "cantidad": 340
    },
    {
      "id": 26,
      "nombre": "Cerveza Original Schlenkerla",
      "descripcion": "Una cerveza ahumada con un toque de malta tostada y humo. Perfecta para acompañar carnes a la parrilla.",
      "categoria": "Smoked Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689274/HopPassion/26.png",
      "precio_dolares": 6.79,
      "pais_origen": "Perú",
      "grados_alcohol": 7.8,
      "cantidad": 340
    },
    {
      "id": 27,
      "nombre": "Dorada Cerveza rubia nacional Pilsen",
      "descripcion": "Una cerveza dorada con un toque de miel y vainilla. Su sabor dulce y suave la hace perfecta para los paladares más exigentes.",
      "categoria": "Golden Ale",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689281/HopPassion/27.png",
      "precio_dolares": 5.79,
      "pais_origen": "México",
      "grados_alcohol": 6.2,
      "cantidad": 340
    },
    {
      "id": 28,
      "nombre": "Cerveza BEAR BEER",
      "descripcion": "Una cerveza refinada con un toque de madera y vainilla. Envejecida en barricas de roble para un sabor excepcional.",
      "categoria": "Barrel-Aged Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689287/HopPassion/28.png",
      "precio_dolares": 7.99,
      "pais_origen": "Colombia",
      "grados_alcohol": 8.5,
      "cantidad": 340
    },
    {
      "id": 29,
      "nombre": "Cerveza Delirium Red Frutal Delirium",
      "descripcion": "Una cerveza frutal con un aroma a frutas del bosque y un sabor refrescante. Ideal para los amantes de los sabores naturales.",
      "categoria": "Fruit Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689295/HopPassion/29.png",
      "precio_dolares": 4.49,
      "pais_origen": "Argentina",
      "grados_alcohol": 5.5,
      "cantidad": 330
    },
    {
      "id": 30,
      "nombre": "Cerveza BBC",
      "descripcion": "Una cerveza con un fuerte sabor a café recién tostado y un toque de chocolate negro. Ideal para los amantes del café.",
      "categoria": "Coffee Stout",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689301/HopPassion/30.png",
      "precio_dolares": 6.99,
      "pais_origen": "Perú",
      "grados_alcohol": 7.5,
      "cantidad": 330
    },
    {
      "id": 31,
      "nombre": "Cerveza Mahou Rosé",
      "descripcion": "Una cerveza refrescante con un toque de limón y hierbas frescas. Ideal para disfrutar en días calurosos.",
      "categoria": "Wheat Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689306/HopPassion/31.png",
      "precio_dolares": 5.29,
      "pais_origen": "México",
      "grados_alcohol": 4.8,
      "cantidad": 330
    },
    {
      "id": 32,
      "nombre": "Cerveza Patagonia",
      "descripcion": "Una cerveza ligera y baja en calorías, ideal para mantenerse en forma sin renunciar al sabor.",
      "categoria": "Light Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689311/HopPassion/32.png",
      "precio_dolares": 3.79,
      "pais_origen": "Colombia",
      "grados_alcohol": 3.8,
      "cantidad": 330
    },
    {
      "id": 33,
      "nombre": "Von Winning Kalkofen GG",
      "descripcion": "Una cerveza exótica con un aroma único a frutas tropicales y especias. Su sabor intenso y afrutado la hace ideal para ocasiones especiales.",
      "categoria": "Fruit Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689317/HopPassion/33.png",
      "precio_dolares": 4.99,
      "pais_origen": "Argentina",
      "grados_alcohol": 6.5,
      "cantidad": 355
    },
    {
      "id": 34,
      "nombre": "Cerveza ale",
      "descripcion": "Una cerveza premium con un sabor suave y refinado, enriquecido con lúpulos aromáticos. Para ocasiones especiales.",
      "categoria": "Premium Lager",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689323/HopPassion/34.png",
      "precio_dolares": 6.79,
      "pais_origen": "Perú",
      "grados_alcohol": 5.9,
      "cantidad": 340
    },
    {
      "id": 35,
      "nombre": "Cerveza Two Broders",
      "descripcion": "Una cerveza robusta y llena de carácter, con notas de café y chocolate negro. Perfecta para los amantes de las cervezas oscuras.",
      "categoria": "Stout",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689329/HopPassion/35.png",
      "precio_dolares": 5.79,
      "pais_origen": "México",
      "grados_alcohol": 7.2,
      "cantidad": 500
    },
    {
      "id": 36,
      "nombre": "Cerveza artesanal Lager",
      "descripcion": "Una cerveza tradicional con raíces históricas y un sabor auténtico. Ideal para quienes aprecian la herencia cervecera.",
      "categoria": "Traditional Ale",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689335/HopPassion/36.png",
      "precio_dolares": 4.29,
      "pais_origen": "Colombia",
      "grados_alcohol": 5.2,
      "cantidad": 330
    },
    {
      "id": 37,
      "nombre": "Cerveza 5",
      "descripcion": "Una cerveza de invierno con notas de canela y nuez moscada. Perfecta para calentarse en las noches frías.",
      "categoria": "Winter Warmer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689341/HopPassion/37.png",
      "precio_dolares": 7.49,
      "pais_origen": "Argentina",
      "grados_alcohol": 7.2,
      "cantidad": 450
    },
    {
      "id": 38,
      "nombre": "Boj Ahumada",
      "descripcion": "Una cerveza ahumada con un toque de malta tostada y humo. Perfecta para acompañar carnes a la parrilla.",
      "categoria": "Smoked Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689347/HopPassion/38.png",
      "precio_dolares": 6.79,
      "pais_origen": "Perú",
      "grados_alcohol": 7.8,
      "cantidad": 330
    },
    {
      "id": 39,
      "nombre": "Cerveza Red Hill",
      "descripcion": "Una cerveza dorada con un toque de miel y vainilla. Su sabor dulce y suave la hace perfecta para los paladares más exigentes.",
      "categoria": "Golden Ale",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689353/HopPassion/39.png",
      "precio_dolares": 5.79,
      "pais_origen": "México",
      "grados_alcohol": 6.2,
      "cantidad": 330
    },
    {
      "id": 40,
      "nombre": "Cerveza Mahou Clásica",
      "descripcion": "Una cerveza refinada con un toque de madera y vainilla. Envejecida en barricas de roble para un sabor excepcional.",
      "categoria": "Barrel-Aged Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689358/HopPassion/40.png",
      "precio_dolares": 7.99,
      "pais_origen": "Colombia",
      "grados_alcohol": 8.5,
      "cantidad": 350
    },
    {
      "id": 41,
      "nombre": "Cerveza GREENGA",
      "descripcion": "Una cerveza frutal con un aroma a frutas del bosque y un sabor refrescante. Ideal para los amantes de los sabores naturales.",
      "categoria": "Fruit Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689364/HopPassion/41.png",
      "precio_dolares": 4.49,
      "pais_origen": "Argentina",
      "grados_alcohol": 6.1,
      "cantidad": 350
    },
    {
      "id": 42,
      "nombre": "Cerveza Tacoa",
      "descripcion": "Una cerveza con un fuerte sabor a café recién tostado y un toque de chocolate negro. Ideal para los amantes del café.",
      "categoria": "Coffee Stout",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689369/HopPassion/42.png",
      "precio_dolares": 6.99,
      "pais_origen": "Perú",
      "grados_alcohol": 6.2,
      "cantidad": 340
    },
    {
      "id": 43,
      "nombre": "Cerveza Ruby",
      "descripcion": "Una cerveza refrescante con un toque de limón y hierbas frescas. Ideal para disfrutar en días calurosos.",
      "categoria": "Wheat Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689376/HopPassion/43.png",
      "precio_dolares": 5.29,
      "pais_origen": "México",
      "grados_alcohol": 4.5,
      "cantidad": 340
    },
    {
      "id": 44,
      "nombre": "CERVEZA MILLER LITE LATA",
      "descripcion": "Una cerveza ligera y baja en calorías, ideal para mantenerse en forma sin renunciar al sabor.",
      "categoria": "Light Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689384/HopPassion/44.png",
      "precio_dolares": 3.79,
      "pais_origen": "Colombia",
      "grados_alcohol": 4.2,
      "cantidad": 340
    },
    {
      "id": 45,
      "nombre": "Cerveza oscura secreto de los monjes",
      "descripcion": "Una cerveza exótica con un aroma único a frutas tropicales y especias. Su sabor intenso y afrutado la hace ideal para ocasiones especiales.",
      "categoria": "Fruit Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689401/HopPassion/45.png",
      "precio_dolares": 4.99,
      "pais_origen": "Argentina",
      "grados_alcohol": 6.5,
      "cantidad": 355
    },
    {
      "id": 46,
      "nombre": "Cerveza Tuborg",
      "descripcion": "Una cerveza premium con un sabor suave y refinado, enriquecido con lúpulos aromáticos. Para ocasiones especiales.",
      "categoria": "Premium Lager",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689406/HopPassion/46.png",
      "precio_dolares": 6.79,
      "pais_origen": "Perú",
      "grados_alcohol": 5.9,
      "cantidad": 355
    },
    {
      "id": 47,
      "nombre": "Weissbier Naturtrüb",
      "descripcion": "Una cerveza robusta y llena de carácter, con notas de café y chocolate negro. Perfecta para los amantes de las cervezas oscuras.",
      "categoria": "Stout",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689411/HopPassion/47.png",
      "precio_dolares": 5.79,
      "pais_origen": "México",
      "grados_alcohol": 7.2,
      "cantidad": 400
    },
    {
      "id": 48,
      "nombre": "Cerveza Tradicional Canes",
      "descripcion": "Una cerveza tradicional con raíces históricas y un sabor auténtico. Ideal para quienes aprecian la herencia cervecera.",
      "categoria": "Traditional Ale",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689418/HopPassion/48.png",
      "precio_dolares": 4.29,
      "pais_origen": "Colombia",
      "grados_alcohol": 5.2,
      "cantidad": 330
    },
    {
      "id": 49,
      "nombre": "Cerveza Schloss Eggenberg ",
      "descripcion": "Una cerveza de invierno con notas de canela y nuez moscada. Perfecta para calentarse en las noches frías.",
      "categoria": "Winter Warmer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689423/HopPassion/49.png",
      "precio_dolares": 7.49,
      "pais_origen": "Argentina",
      "grados_alcohol": 6.0,
      "cantidad": 330
    },
    {
      "id": 50,
      "nombre": "Cerveza Dos Equis",
      "descripcion": "Una cerveza ahumada con un toque de malta tostada y humo. Perfecta para acompañar carnes a la parrilla.",
      "categoria": "Smoked Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689430/HopPassion/50.png",
      "precio_dolares": 6.79,
      "pais_origen": "Perú",
      "grados_alcohol": 7.8,
      "cantidad": 330
    },
    {
      "id": 51,
      "nombre": "CERVEZA CUSQUEÑA DORADA",
      "descripcion": "Una cerveza dorada con un toque de miel y vainilla. Su sabor dulce y suave la hace perfecta para los paladares más exigentes.",
      "categoria": "Golden Ale",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689436/HopPassion/51.png",
      "precio_dolares": 5.79,
      "pais_origen": "México",
      "grados_alcohol": 6.2,
      "cantidad": 310
    },
    {
      "id": 52,
      "nombre": "Cerveza Forseti Dry Stout",
      "descripcion": "Una cerveza refinada con un toque de madera y vainilla. Envejecida en barricas de roble para un sabor excepcional.",
      "categoria": "Barrel-Aged Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689441/HopPassion/52.png",
      "precio_dolares": 7.99,
      "pais_origen": "Colombia",
      "grados_alcohol": 5.9,
      "cantidad": 310
    },
    {
      "id": 53,
      "nombre": "Cerveza Frutal AAA",
      "descripcion": "Una cerveza frutal con un aroma a frutas del bosque y un sabor refrescante. Ideal para los amantes de los sabores naturales.",
      "categoria": "Fruit Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689450/HopPassion/53.png",
      "precio_dolares": 4.49,
      "pais_origen": "Argentina",
      "grados_alcohol": 5.5,
      "cantidad": 310
    },
    {
      "id": 54,
      "nombre": "Cerveza Artesanal Trama Belgian Blond Ale",
      "descripcion": "Una cerveza con un fuerte sabor a café recién tostado y un toque de chocolate negro. Ideal para los amantes del café.",
      "categoria": "Coffee Stout",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689456/HopPassion/54.png",
      "precio_dolares": 6.99,
      "pais_origen": "Perú",
      "grados_alcohol": 7.5,
      "cantidad": 330
    },
    {
      "id": 55,
      "nombre": "Cerveza Refrescante ACD ALC",
      "descripcion": "Una cerveza refrescante con un toque de limón y hierbas frescas. Ideal para disfrutar en días calurosos.",
      "categoria": "Wheat Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689462/HopPassion/55.png",
      "precio_dolares": 5.29,
      "pais_origen": "México",
      "grados_alcohol": 4.5,
      "cantidad": 355
    },
    {
      "id": 56,
      "nombre": "Cerveza Minverva",
      "descripcion": "Una cerveza ligera y baja en calorías, ideal para mantenerse en forma sin renunciar al sabor.",
      "categoria": "Light Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689469/HopPassion/56.png",
      "precio_dolares": 3.79,
      "pais_origen": "Colombia",
      "grados_alcohol": 3.8,
      "cantidad": 355
    },
    {
      "id": 57,
      "nombre": "Cerveza Summer Papa Dry Hop",
      "descripcion": "Una cerveza exótica con un aroma único a frutas tropicales y especias. Su sabor intenso y afrutado la hace ideal para ocasiones especiales.",
      "categoria": "Fruit Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689476/HopPassion/57.png",
      "precio_dolares": 4.99,
      "pais_origen": "Argentina",
      "grados_alcohol": 6.5,
      "cantidad": 355
    },
    {
      "id": 58,
      "nombre": "Cerveza Club verde",
      "descripcion": "Una cerveza premium con un sabor suave y refinado, enriquecido con lúpulos aromáticos. Para ocasiones especiales.",
      "categoria": "Premium Lager",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689484/HopPassion/58.png",
      "precio_dolares": 6.79,
      "pais_origen": "Perú",
      "grados_alcohol": 5.9,
      "cantidad": 355
    },
    {
      "id": 59,
      "nombre": "Cerveza Robusta Victoria",
      "descripcion": "Una cerveza robusta y llena de carácter, con notas de café y chocolate negro. Perfecta para los amantes de las cervezas oscuras.",
      "categoria": "Stout",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689489/HopPassion/59.png",
      "precio_dolares": 5.79,
      "pais_origen": "México",
      "grados_alcohol": 7.2,
      "cantidad": 500
    },
    {
      "id": 60,
      "nombre": "Cerveza Damm Black Drop",
      "descripcion": "Una cerveza tradicional con raíces históricas y un sabor auténtico. Ideal para quienes aprecian la herencia cervecera.",
      "categoria": "Traditional Ale",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689494/HopPassion/60.png",
      "precio_dolares": 4.29,
      "pais_origen": "Colombia",
      "grados_alcohol": 5.2,
      "cantidad": 330
    },
    {
      "id": 61,
      "nombre": "Cerveza Eggenberg Samichlaus Helles",
      "descripcion": "Una cerveza de invierno con notas de canela y nuez moscada. Perfecta para calentarse en las noches frías.",
      "categoria": "Winter Warmer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689499/HopPassion/61.png",
      "precio_dolares": 7.49,
      "pais_origen": "Argentina",
      "grados_alcohol": 6.0,
      "cantidad": 330
    },
    {
      "id": 62,
      "nombre": "Cerveza Ahumada ABADIA",
      "descripcion": "Una cerveza ahumada con un toque de malta tostada y humo. Perfecta para acompañar carnes a la parrilla.",
      "categoria": "Smoked Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689506/HopPassion/62.png",
      "precio_dolares": 6.79,
      "pais_origen": "Perú",
      "grados_alcohol": 7.8,
      "cantidad": 355
    },
    {
      "id": 63,
      "nombre": "Cerveza Dorada Club Colombia",
      "descripcion": "Una cerveza dorada con un toque de miel y vainilla. Su sabor dulce y suave la hace perfecta para los paladares más exigentes.",
      "categoria": "Golden Ale",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689511/HopPassion/63.png",
      "precio_dolares": 5.79,
      "pais_origen": "México",
      "grados_alcohol": 6.2,
      "cantidad": 355
    },
    {
      "id": 64,
      "nombre": "Cerveza Kunstmann Torobayo",
      "descripcion": "Una cerveza refinada con un toque de madera y vainilla. Envejecida en barricas de roble para un sabor excepcional.",
      "categoria": "Barrel-Aged Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689517/HopPassion/64.png",
      "precio_dolares": 7.99,
      "pais_origen": "Colombia",
      "grados_alcohol": 8.5,
      "cantidad": 355
    },
    {
      "id": 65,
      "nombre": "Cerveza artesanal April",
      "descripcion": "Una cerveza frutal con un aroma a frutas del bosque y un sabor refrescante. Ideal para los amantes de los sabores naturales.",
      "categoria": "Fruit Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689523/HopPassion/65.png",
      "precio_dolares": 4.49,
      "pais_origen": "Argentina",
      "grados_alcohol": 5.5,
      "cantidad": 340
    },
    {
      "id": 66,
      "nombre": "Choco Stout",
      "descripcion": "Una cerveza con un fuerte sabor a café recién tostado y un toque de chocolate negro. Ideal para los amantes del café.",
      "categoria": "Coffee Stout",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689529/HopPassion/66.png",
      "precio_dolares": 6.99,
      "pais_origen": "Perú",
      "grados_alcohol": 6.0,
      "cantidad": 500
    },
    {
      "id": 67,
      "nombre": "Dominga Kolsh Botella",
      "descripcion": "Una cerveza refrescante con un toque de limón y hierbas frescas. Ideal para disfrutar en días calurosos.",
      "categoria": "Wheat Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689541/HopPassion/67.png",
      "precio_dolares": 5.29,
      "pais_origen": "México",
      "grados_alcohol": 4.5,
      "cantidad": 330
    },
    {
      "id": 68,
      "nombre": "Cerveza Bud Light",
      "descripcion": "Una cerveza ligera y baja en calorías, ideal para mantenerse en forma sin renunciar al sabor.",
      "categoria": "Light Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689548/HopPassion/68.png",
      "precio_dolares": 3.79,
      "pais_origen": "Colombia",
      "grados_alcohol": 3.8,
      "cantidad": 330
    },
    {
      "id": 69,
      "nombre": "Cerveza Estrella Damm",
      "descripcion": "Una cerveza exótica con un aroma único a frutas tropicales y especias. Su sabor intenso y afrutado la hace ideal para ocasiones especiales.",
      "categoria": "Fruit Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689553/HopPassion/69.png",
      "precio_dolares": 4.99,
      "pais_origen": "Argentina",
      "grados_alcohol": 6.5,
      "cantidad": 330
    },
    {
      "id": 70,
      "nombre": "Cerveza Premium Royal Dutch",
      "descripcion": "Una cerveza premium con un sabor suave y refinado, enriquecido con lúpulos aromáticos. Para ocasiones especiales.",
      "categoria": "Premium Lager",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689560/HopPassion/70.png",
      "precio_dolares": 6.79,
      "pais_origen": "Perú",
      "grados_alcohol": 5.0,
      "cantidad": 330
    },
    {
      "id": 71,
      "nombre": "Wendlandt Harry Polanco Red Ale",
      "descripcion": "Una cerveza robusta y llena de carácter, con notas de café y chocolate negro. Perfecta para los amantes de las cervezas oscuras.",
      "categoria": "Stout",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689568/HopPassion/71.png",
      "precio_dolares": 5.79,
      "pais_origen": "México",
      "grados_alcohol": 7.2,
      "cantidad": 355
    },
    {
      "id": 72,
      "nombre": "Cerveza Casa Bruja Tres Tristes Tigres",
      "descripcion": "Una cerveza tradicional con raíces históricas y un sabor auténtico. Ideal para quienes aprecian la herencia cervecera.",
      "categoria": "Traditional Ale",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689577/HopPassion/72.png",
      "precio_dolares": 4.29,
      "pais_origen": "Colombia",
      "grados_alcohol": 5.2,
      "cantidad": 355
    },
    {
      "id": 73,
      "nombre": "Baja Brewing Black Ale",
      "descripcion": "Una cerveza de invierno con notas de canela y nuez moscada. Perfecta para calentarse en las noches frías.",
      "categoria": "Winter Warmer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689589/HopPassion/73.png",
      "precio_dolares": 7.49,
      "pais_origen": "Argentina",
      "grados_alcohol": 6.0,
      "cantidad": 355
    },
    {
      "id": 74,
      "nombre": "Aecht Schlenkerla Eiche",
      "descripcion": "Una cerveza ahumada con un toque de malta tostada y humo. Perfecta para acompañar carnes a la parrilla.",
      "categoria": "Smoked Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689595/HopPassion/74.png",
      "precio_dolares": 6.79,
      "pais_origen": "Perú",
      "grados_alcohol": 7.8,
      "cantidad": 340
    },
    {
      "id": 75,
      "nombre": "Cerveza Dorada",
      "descripcion": "Una cerveza dorada con un toque de miel y vainilla. Su sabor dulce y suave la hace perfecta para los paladares más exigentes.",
      "categoria": "Golden Ale",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689601/HopPassion/75.png",
      "precio_dolares": 5.79,
      "pais_origen": "México",
      "grados_alcohol": 6.0,
      "cantidad": 1200
    },
    {
      "id": 76,
      "nombre": "Cerveza Refinada AMSTEL",
      "descripcion": "Una cerveza refinada con un toque de madera y vainilla. Envejecida en barricas de roble para un sabor excepcional.",
      "categoria": "Barrel-Aged Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689606/HopPassion/76.png",
      "precio_dolares": 7.99,
      "pais_origen": "Colombia",
      "grados_alcohol": 0.0,
      "cantidad": 500
    },
    {
      "id": 77,
      "nombre": "Nueva Kross Berries",
      "descripcion": "Una cerveza frutal con un aroma a frutas del bosque y un sabor refrescante. Ideal para los amantes de los sabores naturales.",
      "categoria": "Fruit Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689612/HopPassion/77.png",
      "precio_dolares": 4.49,
      "pais_origen": "Argentina",
      "grados_alcohol": 5.5,
      "cantidad": 330
    },
    {
      "id": 78,
      "nombre": "Muster Massacre del Diablo",
      "descripcion": "Una cerveza con un fuerte sabor a café recién tostado y un toque de chocolate negro. Ideal para los amantes del café.",
      "categoria": "Coffee Stout",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689618/HopPassion/78.png",
      "precio_dolares": 6.99,
      "pais_origen": "Perú",
      "grados_alcohol": 7.5,
      "cantidad": 340
    },
    {
      "id": 79,
      "nombre": "Cerveza Presidente Golden Light",
      "descripcion": "Una cerveza refrescante con un toque de limón y hierbas frescas. Ideal para disfrutar en días calurosos.",
      "categoria": "Wheat Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689624/HopPassion/79.png",
      "precio_dolares": 5.29,
      "pais_origen": "México",
      "grados_alcohol": 4.5,
      "cantidad": 330
    },
    {
      "id": 80,
      "nombre": "Cerveza Eel River IPA",
      "descripcion": "Una cerveza ligera y baja en calorías, ideal para mantenerse en forma sin renunciar al sabor.",
      "categoria": "Light Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689630/HopPassion/80.png",
      "precio_dolares": 3.79,
      "pais_origen": "Colombia",
      "grados_alcohol": 3.8,
      "cantidad": 340
    },
    {
      "id": 81,
      "nombre": "Cerveza Weihenstephaner Pils",
      "descripcion": "Una cerveza exótica con un aroma único a frutas tropicales y especias. Su sabor intenso y afrutado la hace ideal para ocasiones especiales.",
      "categoria": "Fruit Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689648/HopPassion/81.png",
      "precio_dolares": 4.99,
      "pais_origen": "Argentina",
      "grados_alcohol": 6.5,
      "cantidad": 330
    },
    {
      "id": 82,
      "nombre": "Cerveza Premium Rabieta",
      "descripcion": "Una cerveza premium con un sabor suave y refinado, enriquecido con lúpulos aromáticos. Para ocasiones especiales.",
      "categoria": "Premium Lager",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689655/HopPassion/82.png",
      "precio_dolares": 6.79,
      "pais_origen": "Perú",
      "grados_alcohol": 5.9,
      "cantidad": 500
    },
    {
      "id": 83,
      "nombre": "Tu Water & Vuur De Molen",
      "descripcion": "Una cerveza robusta y llena de carácter, con notas de café y chocolate negro. Perfecta para los amantes de las cervezas oscuras.",
      "categoria": "Stout",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689661/HopPassion/83.png",
      "precio_dolares": 5.79,
      "pais_origen": "México",
      "grados_alcohol": 7.2,
      "cantidad": 450
    },
    {
      "id": 84,
      "nombre": "Quebec Trois Pistoles",
      "descripcion": "Una cerveza tradicional con raíces históricas y un sabor auténtico. Ideal para quienes aprecian la herencia cervecera.",
      "categoria": "Traditional Ale",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689666/HopPassion/84.png",
      "precio_dolares": 4.29,
      "pais_origen": "Colombia",
      "grados_alcohol": 9.0,
      "cantidad": 341
    },
    {
      "id": 85,
      "nombre": "Cerveza Shofferhofer Sab. Pomel Botella",
      "descripcion": "Una cerveza de invierno con notas de canela y nuez moscada. Perfecta para calentarse en las noches frías.",
      "categoria": "Winter Warmer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689672/HopPassion/85.png",
      "precio_dolares": 7.49,
      "pais_origen": "Argentina",
      "grados_alcohol": 6.0,
      "cantidad": 330
    },
    {
      "id": 86,
      "nombre": "Cerveza Guinness Original",
      "descripcion": "Una cerveza ahumada con un toque de malta tostada y humo. Perfecta para acompañar carnes a la parrilla.",
      "categoria": "Smoked Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689677/HopPassion/86.png",
      "precio_dolares": 6.79,
      "pais_origen": "Perú",
      "grados_alcohol": 7.8,
      "cantidad": 342
    },
    {
      "id": 87,
      "nombre": "Cerveza Miller",
      "descripcion": "Una cerveza dorada con un toque de miel y vainilla. Su sabor dulce y suave la hace perfecta para los paladares más exigentes.",
      "categoria": "Golden Ale",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689683/HopPassion/87.png",
      "precio_dolares": 5.79,
      "pais_origen": "México",
      "grados_alcohol": 6.2,
      "cantidad": 330
    },
    {
      "id": 88,
      "nombre": "Cerveza Refinada Löwenbräu Oktoberfestbier",
      "descripcion": "Una cerveza refinada con un toque de madera y vainilla. Envejecida en barricas de roble para un sabor excepcional.",
      "categoria": "Barrel-Aged Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689688/HopPassion/88.png",
      "precio_dolares": 7.99,
      "pais_origen": "Colombia",
      "grados_alcohol": 8.5,
      "cantidad": 340
    },
    {
      "id": 89,
      "nombre": "Hofbrau Munchen Weisse",
      "descripcion": "Una cerveza frutal con un aroma a frutas del bosque y un sabor refrescante. Ideal para los amantes de los sabores naturales.",
      "categoria": "Fruit Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689693/HopPassion/89.png",
      "precio_dolares": 4.49,
      "pais_origen": "Argentina",
      "grados_alcohol": 5.5,
      "cantidad": 330
    },
    {
      "id": 90,
      "nombre": "Cerveza Cumbres",
      "descripcion": "Una cerveza con un fuerte sabor a café recién tostado y un toque de chocolate negro. Ideal para los amantes del café.",
      "categoria": "Coffee Stout",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689701/HopPassion/90.png",
      "precio_dolares": 6.99,
      "pais_origen": "Perú",
      "grados_alcohol": 7.5,
      "cantidad": 400
    },
    {
      "id": 91,
      "nombre": "Cerveza St. Wendeler Pils",
      "descripcion": "Una cerveza refrescante con un toque de limón y hierbas frescas. Ideal para disfrutar en días calurosos.",
      "categoria": "Wheat Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689715/HopPassion/91.png",
      "precio_dolares": 5.29,
      "pais_origen": "México",
      "grados_alcohol": 4.6,
      "cantidad": 330
    },
    {
      "id": 92,
      "nombre": "Cerveza Bruder Rosa Chocolate",
      "descripcion": "Una cerveza ligera y baja en calorías, ideal para mantenerse en forma sin renunciar al sabor.",
      "categoria": "Light Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689721/HopPassion/92.png",
      "precio_dolares": 3.79,
      "pais_origen": "Colombia",
      "grados_alcohol": 3.8,
      "cantidad": 330
    },
    {
      "id": 93,
      "nombre": "Cerveza Estrella Galicia",
      "descripcion": "Una cerveza exótica con un aroma único a frutas tropicales y especias. Su sabor intenso y afrutado la hace ideal para ocasiones especiales.",
      "categoria": "Fruit Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689728/HopPassion/93.png",
      "precio_dolares": 4.99,
      "pais_origen": "Argentina",
      "grados_alcohol": 6.5,
      "cantidad": 330
    },
    {
      "id": 94,
      "nombre": "Cerveza Premium Estrella de Levante",
      "descripcion": "Una cerveza premium con un sabor suave y refinado, enriquecido con lúpulos aromáticos. Para ocasiones especiales.",
      "categoria": "Premium Lager",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689735/HopPassion/94.png",
      "precio_dolares": 6.79,
      "pais_origen": "Perú",
      "grados_alcohol": 0.0,
      "cantidad": 340
    },
    {
      "id": 95,
      "nombre": "Cerveza Robusta Volcanes del Sur",
      "descripcion": "Una cerveza robusta y llena de carácter, con notas de café y chocolate negro. Perfecta para los amantes de las cervezas oscuras.",
      "categoria": "Stout",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689745/HopPassion/95.png",
      "precio_dolares": 5.79,
      "pais_origen": "México",
      "grados_alcohol": 7.2,
      "cantidad": 1200
    },
    {
      "id": 96,
      "nombre": "Cerveza Ordum Cerveza craft Ordum Lager",
      "descripcion": "Una cerveza tradicional con raíces históricas y un sabor auténtico. Ideal para quienes aprecian la herencia cervecera.",
      "categoria": "Traditional Ale",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689759/HopPassion/96.png",
      "precio_dolares": 4.29,
      "pais_origen": "Colombia",
      "grados_alcohol": 5.2,
      "cantidad": 355
    },
    {
      "id": 97,
      "nombre": "Cerveza de Invierno INNIS & GUNN",
      "descripcion": "Una cerveza de invierno con notas de canela y nuez moscada. Perfecta para calentarse en las noches frías.",
      "categoria": "Winter Warmer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689765/HopPassion/97.png",
      "precio_dolares": 7.49,
      "pais_origen": "Argentina",
      "grados_alcohol": 6.0,
      "cantidad": 355
    },
    {
      "id": 98,
      "nombre": "Cerveza Ahumada Rosa Blanca",
      "descripcion": "Una cerveza ahumada con un toque de malta tostada y humo. Perfecta para acompañar carnes a la parrilla.",
      "categoria": "Smoked Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689770/HopPassion/98.png",
      "precio_dolares": 6.79,
      "pais_origen": "Perú",
      "grados_alcohol": 7.8,
      "cantidad": 355
    },
    {
      "id": 99,
      "nombre": "Cerveza Dorada Kozel",
      "descripcion": "Una cerveza dorada con un toque de miel y vainilla. Su sabor dulce y suave la hace perfecta para los paladares más exigentes.",
      "categoria": "Golden Ale",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689775/HopPassion/99.png",
      "precio_dolares": 5.79,
      "pais_origen": "México",
      "grados_alcohol": 6.2,
      "cantidad": 330
    },
    {
      "id": 100,
      "nombre": "Cerveza Refinada Brahma",
      "descripcion": "Una cerveza refinada con un toque de madera y vainilla. Envejecida en barricas de roble para un sabor excepcional.",
      "categoria": "Barrel-Aged Beer",
      "imagen": "https://res.cloudinary.com/dkwvnp3ut/image/upload/v1695689780/HopPassion/100.png",
      "precio_dolares": 7.99,
      "pais_origen": "Colombia",
      "grados_alcohol": 3.5,
      "cantidad": 340
    }
  ]

  module.exports= cervezas;